title: CSC 481/681 Principles of Computer Security
description: Course website for CSC 481/681

remote_theme: "mmistakes/minimal-mistakes@4.24.4"

plugins:
  - jekyll-remote-theme

# Top bar
nav:
  - title: "Home"
    url: /
  - title: "Syllabus"
    url: /CSC481681-Spring 2026-Syllabus
  - title: "Schedule"
    url: /CSC481681-Spring 2026-Schedule
  - title: "Assignments"
    url: /CSC481681-Spring 2026-Assignments

# Default layout
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single


