title: CSC 481/681 Principles of Computer Security
description: Course website for CSC 481/681

theme: "just-the-docs"

# 构建导航栏
just_the_docs:
  nav_order: 1
  logo: false
  search_enabled: true

# Top bar
nav:
  - title: "Home"
    url: /
  - title: "Syllabus"
    url: /CSC481681-Spring 2026-Syllabus
  - title: "Schedule"
    url: /CSC481681-Spring 2026-Schedule
  - title: "Assignments"
    url: /CSC481681-Spring 2026-Assignments




